const app = document.getElementById("app");
let token = localStorage.getItem("token"), user = JSON.parse(localStorage.getItem("user") || "null");
const api = async (path, opt = {}) => {
  opt.headers = { ...(opt.headers || {}), "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) };
  const r = await fetch("/api" + path, opt);
  if (!r.ok) {
    const body = await r.json().catch(() => ({}));
    const detail = Array.isArray(body.detail)
      ? body.detail.map((item) => item.msg).join(", ")
      : body.detail;
    throw new Error(detail || "Something went wrong");
  }
  return r.json();
};
function auth() { app.innerHTML = `<main class="auth"><section class="card"><div class="logo-big">Argue<span>Well</span></div><p class="muted">Your local debate and presentation coach.</p><div id="authbox"></div></section></main>`; showLogin(); }
function showLogin() { document.getElementById("authbox").innerHTML = `<h2>Welcome back</h2><div class="field"><label>Email</label><input id="email" type="email"></div><div class="field"><label>Password</label><input id="password" type="password"></div><div id="err"></div><button class="btn primary" onclick="login()">Sign in</button><button class="btn ghost" onclick="showRegister()">Create an account</button>`; }
function showRegister() { document.getElementById("authbox").innerHTML = `<h2>Start improving</h2><div class="field"><label>Name</label><input id="name"></div><div class="field"><label>Email</label><input id="email" type="email"></div><div class="field"><label>Password</label><input id="password" type="password" placeholder="8+ characters"></div><div id="err"></div><button class="btn primary" onclick="register()">Create account</button><button class="btn ghost" onclick="showLogin()">I already have an account</button>`; }
const fieldValue = (id) => document.getElementById(id).value.trim();
async function login() {
  try {
    save(await api("/auth/login", {
      method: "POST",
      body: JSON.stringify({ email: fieldValue("email"), password: document.getElementById("password").value })
    }));
  } catch (e) { document.getElementById("err").innerHTML = `<div class="alert">${e.message}</div>`; }
}
async function register() {
  try {
    const nameValue = fieldValue("name");
    const emailValue = fieldValue("email");
    const passwordValue = document.getElementById("password").value;
    if (!nameValue || !emailValue || passwordValue.length < 8) {
      throw new Error("Enter a name, a valid email, and a password with at least 8 characters.");
    }
    save(await api("/auth/register", {
      method: "POST",
      body: JSON.stringify({
        name: nameValue,
        email: emailValue,
        password: passwordValue
      })
    }));
  } catch (e) { document.getElementById("err").innerHTML = `<div class="alert">${e.message}</div>`; }
}
function save(x) { token = x.access_token; user = x.user; localStorage.setItem("token", token); localStorage.setItem("user", JSON.stringify(user)); render("dashboard"); }
function layout(content, active) { app.innerHTML = `<div class="shell"><aside class="side"><div class="brand">Argue<span>Well</span></div><nav class="nav"><a class="${active === "dashboard" ? "active" : ""}" href="#" onclick="render('dashboard')">Dashboard</a><a class="${active === "new" ? "active" : ""}" href="#" onclick="render('new')">New debate</a><a class="${active === "presentation" ? "active" : ""}" href="#" onclick="render('presentation')">Presentation</a><a class="${active === "media" ? "active" : ""}" href="#" onclick="render('media')">Upload media</a><a class="${active === "plan" ? "active" : ""}" href="#" onclick="render('plan')">Learning plan</a><a class="${active === "profile" ? "active" : ""}" href="#" onclick="render('profile')">Profile</a></nav><button class="btn ghost" style="margin-top:auto" onclick="logout()">Sign out</button></aside><main class="main">${content}</main></div>`; }
async function render(page, id) { if (!token) return auth(); if (page === "new") return newSession(); if (page === "presentation") return presentation(); if (page === "media") return media(); if (page === "plan") return plan(); if (page === "profile") return profile(); if (page === "detail") return detail(id); const d = await api("/dashboard"); const list = d.recent_sessions.map(s => `<div class="session"><div><b>${s.title}</b><div class="muted">${s.topic} · ${new Date(s.created_at).toLocaleDateString()}</div></div><div class="row"><span class="pill">${s.overall_score}/100</span><button class="btn secondary" onclick="render('detail',${s.id})">View</button></div></div>`).join(""); layout(`<div class="top"><div><div class="eyebrow">Practice studio</div><h1>Good to see you, ${user.name.split(" ")[0]}.</h1><p class="muted">Clear arguments, credible evidence, compelling delivery.</p></div><button class="btn primary" onclick="render('new')">+ New session</button></div><div class="grid stats"><div class="card stat"><small>Sessions completed</small><strong>${d.sessions_count}</strong></div><div class="card stat"><small>Average score</small><strong>${d.average_score}</strong></div><div class="card stat"><small>Personal best</small><strong>${d.best_score}</strong></div></div><div class="card" style="margin-top:22px"><div class="top"><h2>Skill snapshot</h2><span class="muted">Trend points: ${d.trend.length}</span></div><div class="row">${Object.entries(d.skills).map(([k,v]) => `<span class="pill">${k}: ${v}</span>`).join("")}</div><h2 style="margin-top:25px">Recent sessions</h2>${list || '<div class="empty">Your first practice session is one click away.</div>'}</div>`, "dashboard"); }
function newSession() { layout(`<div class="top"><div><div class="eyebrow">Practice lab</div><h1>Analyze a debate</h1></div></div><div class="card form"><div class="field"><label>Session title</label><input id="title" placeholder="My policy debate"></div><div class="field"><label>Topic</label><input id="topic" placeholder="Should cities ban single-use plastics?"></div><div class="field"><label>Position</label><select id="position"><option value="for">I support this</option><option value="against">I oppose this</option></select></div><div class="field"><label>Transcript / notes</label><textarea id="transcript"></textarea></div><div id="err"></div><button class="btn primary" onclick="create()">Analyze my argument</button></div>`, "new"); }
async function create() { try { const s = await api("/sessions", { method: "POST", body: JSON.stringify({ title: title.value, topic: topic.value, position: position.value, transcript: transcript.value }) }); render("detail", s.id); } catch (e) { err.innerHTML = `<div class="alert">${e.message}</div>`; } }
function media() { layout(`<div class="top"><div><div class="eyebrow">Speech lab</div><h1>Upload audio or video</h1><p class="muted">Add a transcript for instant local or Groq-backed analysis.</p></div></div><div class="card form"><div class="field"><label>Recording</label><input id="mediafile" type="file" accept="audio/*,video/*"></div><div class="field"><label>Topic</label><input id="mtopic" value="Presentation practice"></div><div class="field"><label>Transcript (optional)</label><textarea id="mtranscript"></textarea></div><div id="err"></div><button class="btn primary" onclick="uploadMedia()">Upload and analyze</button></div>`, "media"); }
async function uploadMedia() { try { const data = new FormData(); data.append("file", mediafile.files[0]); data.append("topic", mtopic.value); data.append("transcript", mtranscript.value); const r = await fetch("/api/media/upload", { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: data }); if (!r.ok) throw new Error((await r.json()).detail || "Upload failed"); const x = await r.json(); layout(`<div class="card"><h2>Upload complete</h2><p>${x.filename} · ${x.size_bytes} bytes · ${x.status}</p><p>${x.transcript_available ? `Overall score: ${x.analysis.overall_score}/100` : "Add a transcript to generate an analysis."}</p></div>`, "media"); } catch (e) { document.getElementById("err").innerHTML = `<div class="alert">${e.message}</div>`; } }
function presentation() { layout(`<div class="top"><div><div class="eyebrow">Delivery lab</div><h1>Analyze a presentation</h1></div></div><div class="card form"><div class="field"><label>Title</label><input id="ptitle" value="Presentation practice"></div><div class="field"><label>Duration (seconds, optional)</label><input id="duration" type="number"></div><div class="field"><label>Transcript</label><textarea id="ptext"></textarea></div><div id="err"></div><button class="btn primary" onclick="analyzePresentation()">Analyze delivery</button></div>`, "presentation"); }
async function analyzePresentation() { try { const x = await api("/presentations/analyze", { method: "POST", body: JSON.stringify({ title: ptitle.value, transcript: ptext.value, duration_seconds: duration.value ? Number(duration.value) : null }) }); layout(`<div class="top"><div><div class="eyebrow">Presentation report</div><h1>${x.presentation.title}</h1></div><span class="pill">${x.overall_score}/100</span></div><div class="card"><h2>Delivery</h2><p>Estimated pace: ${x.pacing_wpm} WPM · Fillers: ${x.filler_words} · Recommended: ${x.presentation.recommended_wpm} WPM</p><h3>Coaching</h3><ul>${x.recommendations.map(r => `<li>${r}</li>`).join("")}</ul></div>`, "presentation"); } catch (e) { err.innerHTML = `<div class="alert">${e.message}</div>`; } }
async function plan() { const p = await api("/coaching/plan"); layout(`<div class="top"><div><div class="eyebrow">Personalized coaching</div><h1>Your learning plan</h1><p class="muted">Focus area: ${p.focus}</p></div></div><div class="card">${p.weeks.map(w => `<div class="session"><b>Week ${w.week}</b><span>${w.goal}</span></div>`).join("")}</div>`, "plan"); }
async function detail(id) { const x = await api(`/sessions/${id}`), a = x.analysis; const metric = (n,v) => `<div class="metric"><header><span>${n}</span><b>${v}</b></header><div class="meter"><i style="width:${v}%"></i></div></div>`; layout(`<div class="top"><div><div class="eyebrow">Session report</div><h1>${x.session.title}</h1><p class="muted">${x.session.topic}</p></div><span class="pill">${x.session.overall_score}/100 overall</span></div><div class="grid two"><div class="card"><h2>Argument quality</h2>${metric("Clarity",a.clarity)}${metric("Evidence",a.evidence)}${metric("Persuasiveness",a.persuasiveness)}${metric("Delivery",a.delivery)}<p class="muted">${a.arguments.word_count} words · ${a.pacing_wpm} WPM · ${a.filler_words} fillers</p></div><div class="card"><h2>Coach's playbook</h2><ul>${a.recommendations.map(r => `<li>${r}</li>`).join("")}</ul><h3>Counterarguments</h3>${a.counterarguments.map(c => `<p><b>${c.claim}</b><br><span class="muted">${c.response}</span></p>`).join("")}</div></div><div class="card" style="margin-top:18px"><h2>Fallacy scan</h2>${a.fallacies.length ? a.fallacies.map(f => `<div class="alert"><b>${f.type}</b> — ${f.excerpt}</div>`).join("") : "<p class='muted'>No common patterns detected.</p>"}<a class="btn secondary" href="/api/sessions/${id}/export?format=csv" target="_blank">Export CSV</a></div>`, "dashboard"); }
function profile() { layout(`<div class="top"><h1>Your profile</h1></div><div class="card form"><div class="field"><label>Name</label><input id="name" value="${user.name}"></div><div class="field"><label>Bio</label><textarea id="bio">${user.bio || ""}</textarea></div><div class="field"><label>Experience</label><select id="experience_level"><option>beginner</option><option>intermediate</option><option>advanced</option><option>expert</option></select></div><div class="field"><label>Debate topics (comma separated)</label><input id="topics" value="${(user.preferred_debate_topics || []).join(", ")}"></div><div class="field"><label>Presentation domains</label><input id="domains" value="${(user.presentation_domains || []).join(", ")}"></div><div class="field"><label>Learning goals</label><input id="goals" value="${(user.learning_goals || []).join(", ")}"></div><div id="msg"></div><button class="btn primary" onclick="updateProfile()">Save changes</button></div>`, "profile"); experience_level.value = user.experience_level || "beginner"; }
async function updateProfile() { const list = id => document.getElementById(id).value.split(",").map(x => x.trim()).filter(Boolean); user = await api("/profile", { method: "PATCH", body: JSON.stringify({ name: name.value, bio: bio.value, experience_level: experience_level.value, preferred_debate_topics: list("topics"), presentation_domains: list("domains"), learning_goals: list("goals") }) }); localStorage.setItem("user", JSON.stringify(user)); msg.innerHTML = "<p class='pill'>Saved</p>"; }
function logout() { localStorage.clear(); token = null; user = null; auth(); } token ? render("dashboard") : auth();
