const app=document.getElementById("app");let token=localStorage.getItem("token"),user=JSON.parse(localStorage.getItem("user")||"null");
const api=async(path,opt={})=>{opt.headers={...(opt.headers||{}), "Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})};const r=await fetch("/api"+path,opt);if(!r.ok)throw new Error((await r.json()).detail||"Something went wrong");return r.json()};
function auth(){app.innerHTML=`<main class="auth"><section class="card"><div class="logo-big">Argue<span>Well</span></div><p class="muted">Your AI-powered debate and presentation coach.</p><div id="authbox"></div></section></main>`;showLogin()}
function showLogin(){document.getElementById("authbox").innerHTML=`<h2>Welcome back</h2><div class="field"><label>Email</label><input id="email" type="email" placeholder="you@example.com"></div><div class="field"><label>Password</label><input id="password" type="password" placeholder="8+ characters"></div><div id="err"></div><button class="btn primary" onclick="login()">Sign in</button><button class="btn ghost" onclick="showRegister()">Create an account</button>`}
function showRegister(){document.getElementById("authbox").innerHTML=`<h2>Start improving</h2><div class="field"><label>Your name</label><input id="name" placeholder="Alex Morgan"></div><div class="field"><label>Email</label><input id="email" type="email"></div><div class="field"><label>Password</label><input id="password" type="password" placeholder="8+ characters"></div><div id="err"></div><button class="btn primary" onclick="register()">Create account</button><button class="btn ghost" onclick="showLogin()">I already have an account</button>`}
async function login(){try{const x=await api("/auth/login",{method:"POST",body:JSON.stringify({email:email.value,password:password.value})});save(x)}catch(e){document.getElementById("err").innerHTML=`<div class="alert">${e.message}</div>`}}
async function register(){try{const x=await api("/auth/register",{method:"POST",body:JSON.stringify({name:name.value,email:email.value,password:password.value})});save(x)}catch(e){document.getElementById("err").innerHTML=`<div class="alert">${e.message}</div>`}}
function save(x){token=x.access_token;user=x.user;localStorage.setItem("token",token);localStorage.setItem("user",JSON.stringify(user));render("dashboard")}
function layout(content,active){app.innerHTML=`<div class="shell"><aside class="side"><div class="brand">Argue<span>Well</span></div><nav class="nav"><a class="${active==="dashboard"?"active":""}" href="#" onclick="render('dashboard')">Dashboard</a><a class="${active==="new"?"active":""}" href="#" onclick="render('new')">New session</a><a class="${active==="profile"?"active":""}" href="#" onclick="render('profile')">Profile</a></nav><button class="btn ghost" style="margin-top:auto" onclick="logout()">Sign out</button></aside><main class="main">${content}</main></div>`}
async function render(page,id){if(!token)return auth();if(page==="new")return newSession();if(page==="profile")return profile();if(page==="detail")return detail(id);const d=await api("/dashboard");const list=d.recent_sessions.map(s=>`<div class="session"><div><b>${s.title}</b><div class="muted">${s.topic} · ${new Date(s.created_at).toLocaleDateString()}</div></div><div class="row"><span class="pill">${s.overall_score}/100</span><button class="btn secondary" onclick="render('detail',${s.id})">View</button></div></div>`).join("");layout(`<div class="top"><div><div class="eyebrow">Your practice studio</div><h1>Good to see you, ${user.name.split(" ")[0]}.</h1><p class="muted">Build arguments that are clear, credible, and compelling.</p></div><button class="btn primary" onclick="render('new')">+ New session</button></div><div class="grid stats"><div class="card stat"><small>Sessions completed</small><strong>${d.sessions_count}</strong><span class="muted">Keep the momentum</span></div><div class="card stat"><small>Average score</small><strong>${d.average_score}</strong><span class="muted">Across all dimensions</span></div><div class="card stat"><small>Personal best</small><strong>${d.best_score}</strong><span class="muted">Your strongest delivery</span></div></div><div class="card" style="margin-top:22px"><div class="top" style="margin-bottom:8px"><h2>Recent sessions</h2><span class="muted">${d.sessions_count} total</span></div>${list||'<div class="empty">Your first practice session is one click away.</div>'}</div>`,"dashboard")}
function newSession(){layout(`<div class="top"><div><div class="eyebrow">Practice lab</div><h1>Analyze a debate</h1><p class="muted">Paste a transcript or your speaking notes for instant coaching.</p></div></div><div class="card form"><div class="field"><label>Session title</label><input id="title" placeholder="My climate policy debate"></div><div class="field"><label>Topic</label><input id="topic" placeholder="Should cities ban single-use plastics?"></div><div class="field"><label>Your position</label><select id="position"><option value="for">I support this</option><option value="against">I oppose this</option></select></div><div class="field"><label>Transcript / notes</label><textarea id="transcript" placeholder="Paste what you said..."></textarea></div><div id="err"></div><button class="btn primary" onclick="create()">Analyze my argument</button></div>`,"new")}
async function create(){try{const s=await api("/sessions",{method:"POST",body:JSON.stringify({title:title.value,topic:topic.value,position:position.value,transcript:transcript.value})});render("detail",s.id)}catch(e){document.getElementById("err").innerHTML=`<div class="alert">${e.message}</div>`}}
async function detail(id){const x=await api(`/sessions/${id}`),a=x.analysis;const metric=(name,v)=>`<div class="metric"><header><span>${name}</span><b>${v}</b></header><div class="meter"><i style="width:${v}%"></i></div></div>`;layout(`<div class="top"><div><div class="eyebrow">Session report</div><h1>${x.session.title}</h1><p class="muted">${x.session.topic} · ${new Date(x.session.created_at).toLocaleDateString()}</p></div><span class="pill">${x.session.overall_score}/100 overall</span></div><div class="grid two"><div class="card"><h2>Argument quality</h2>${metric("Clarity",a.clarity)}${metric("Evidence",a.evidence)}${metric("Persuasiveness",a.persuasiveness)}${metric("Delivery",a.delivery)}<p class="muted">Estimated pace: ${a.pacing_wpm} words/min · Filler words: ${a.filler_words}</p></div><div class="card"><h2>Coach's playbook</h2><h3>Next best moves</h3><ul>${a.recommendations.map(x=>`<li>${x}</li>`).join("")}</ul><h3>Counterarguments to rehearse</h3>${a.counterarguments.map(x=>`<p><b>${x.claim}</b><br><span class="muted">${x.response}</span></p>`).join("")}</div></div><div class="card" style="margin-top:18px"><h2>Fallacy scan</h2>${a.fallacies.length?a.fallacies.map(x=>`<div class="alert"><b>${x.type}</b> — ${x.excerpt}</div>`).join(""):"<p class='muted'>No common fallacy patterns detected. Nice work.</p>"}</div>`,"dashboard")}
function profile(){layout(`<div class="top"><div><div class="eyebrow">Account</div><h1>Your profile</h1></div></div><div class="card form"><div class="field"><label>Name</label><input id="name" value="${user.name}"></div><div class="field"><label>Bio</label><textarea id="bio" placeholder="What are you working on?">${user.bio||""}</textarea></div><div id="msg"></div><button class="btn primary" onclick="updateProfile()">Save changes</button></div>`,"profile")}
async function updateProfile(){const x=await api("/profile",{method:"PATCH",body:JSON.stringify({name:name.value,bio:bio.value})});user=x;localStorage.setItem("user",JSON.stringify(user));document.getElementById("msg").innerHTML="<p class='pill'>Saved</p>"}
function logout(){localStorage.clear();token=null;user=null;auth()} token?render("dashboard"):auth();
