# Generated by Django 6.1.1 on 2026-09-13 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Presentation Deck Review', max_length=255)),
                ('deck_file', models.FileField(blank=True, null=True, upload_to='presentations/')),
                ('total_slides', models.IntegerField(default=1)),
                ('overall_score', models.IntegerField(default=80)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlideEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slide_number', models.IntegerField()),
                ('headline', models.CharField(blank=True, default='', max_length=255)),
                ('word_count', models.IntegerField(default=0)),
                ('density_rating', models.CharField(default='OPTIMAL', max_length=20)),
                ('visual_structure_score', models.IntegerField(default=85)),
                ('clarity_score', models.IntegerField(default=85)),
                ('critique', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['slide_number'],
            },
        ),
        migrations.CreateModel(
            name='SpeechSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Speech Practice Session', max_length=255)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='speeches/')),
                ('transcript', models.TextField()),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('words_per_minute', models.IntegerField(default=140)),
                ('filler_word_count', models.IntegerField(default=0)),
                ('filler_word_breakdown', models.JSONField(default=dict)),
                ('pacing_score', models.IntegerField(default=80)),
                ('articulation_score', models.IntegerField(default=80)),
                ('overall_score', models.IntegerField(default=80)),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
