import { CalendarDays, ChartNoAxesCombined, CircleUserRound, LayoutDashboard, MessageSquare, Settings2, Sparkles, Target, UsersRound, X } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'

const roleLabels = { LEARNER: 'Learner', DEBATE_COACH: 'Debate Coach', EDUCATOR: 'Educator', ADMINISTRATOR: 'Administrator' }

export default function Sidebar({ open, onClose }) {
  const { user } = useAuth()
  const role = String(user?.role || 'LEARNER').toUpperCase()
  const common = [{ to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard }, { to: '/profile', label: 'My profile', icon: CircleUserRound }]
  const roleItems = role === 'LEARNER' ? [{ to: '/skills', label: 'My skills', icon: ChartNoAxesCombined }, { to: '/debates', label: 'Debates', icon: MessageSquare }, { to: '/simulation', label: 'AI simulation', icon: Sparkles }, { to: '/coaching', label: 'Coaching plan', icon: Target }] : role === 'DEBATE_COACH' ? [{ to: '/debates', label: 'Debates', icon: MessageSquare }, { to: '/students', label: 'Students', icon: UsersRound }] : role === 'EDUCATOR' ? [{ to: '/debates', label: 'Class debates', icon: CalendarDays }, { to: '/students', label: 'Students', icon: UsersRound }] : [{ to: '/users', label: 'Users', icon: UsersRound }, { to: '/debates', label: 'Platform debates', icon: MessageSquare }]
  const items = [...common, ...roleItems]
  return <><div className={`fixed inset-0 z-40 bg-ink/30 backdrop-blur-sm lg:hidden ${open ? 'block' : 'hidden'}`} onClick={onClose} /><aside className={`fixed inset-y-0 left-0 z-50 w-72 transform border-r border-white/10 bg-ink px-5 py-6 text-white shadow-2xl transition-transform lg:static lg:z-0 lg:block lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="mb-8 flex items-center justify-between lg:hidden"><span className="font-display text-lg font-bold">Navigation</span><button onClick={onClose} className="rounded-xl p-2 text-slate-300 hover:bg-white/10"><X size={20} /></button></div><div className="mb-8 overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-white/15 to-white/5 p-5 shadow-xl"><div className="mb-4 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-mint shadow-[0_0_12px_#2a9d8f]" /><span className="text-[10px] font-extrabold uppercase tracking-[0.2em] text-slate-300">Live workspace</span></div><p className="truncate font-display text-xl font-bold">{roleLabels[role] || 'Member'}</p><p className="mt-1 truncate text-xs text-slate-300">{user?.email || 'Connect your account'}</p></div><nav className="space-y-2">{items.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} onClick={onClose} className={({ isActive }) => `group flex items-center gap-3 rounded-2xl px-4 py-3 text-sm font-bold transition ${isActive ? 'bg-white text-ink shadow-lg shadow-black/10' : 'text-slate-300 hover:bg-white/10 hover:text-white'}`}><Icon size={18} className="transition group-hover:scale-105" />{label}</NavLink>)}<div className="my-5 border-t border-white/10" /><NavLink to="/settings" onClick={onClose} className={({ isActive }) => `flex items-center gap-3 rounded-2xl px-4 py-3 text-sm font-bold transition ${isActive ? 'bg-white text-ink' : 'text-slate-300 hover:bg-white/10 hover:text-white'}`}><Settings2 size={18} />Settings</NavLink></nav><div className="absolute bottom-6 left-5 right-5 rounded-2xl border border-white/10 bg-white/5 p-4 text-xs leading-5 text-slate-400">Make a clear claim.<br /><span className="text-mint">Support it with evidence.</span></div></aside></>
}
