import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import api from '../services/api'
import { useAuth } from '../context/AuthContext'

export default function DebateDetail() { const { debateId } = useParams(); const { user } = useAuth(); const navigate = useNavigate(); const [debate, setDebate] = useState(null); const [participants, setParticipants] = useState([]); const [position, setPosition] = useState('neutral'); const [error, setError] = useState(''); const [editing, setEditing] = useState(false); const [status, setStatus] = useState('scheduled')
  function load() { return Promise.all([api.get(`/debates/${debateId}`), api.get(`/debates/${debateId}/participants`)]).then(([debateResponse, participantResponse]) => { setDebate(debateResponse.data); setStatus(debateResponse.data.status); setParticipants(participantResponse.data) }).catch(() => setError('Unable to load this session.')) }
  useEffect(() => { load() }, [debateId])
  async function join() { try { await api.post(`/debates/${debateId}/join?position=${position}`); await load() } catch (requestError) { setError(requestError.response?.data?.detail || 'Unable to join session.') } }
  async function removeParticipant(participantId) { await api.delete(`/debates/${debateId}/participants/${participantId}`); await load() }
  async function updateStatus() { try { await api.put(`/debates/${debateId}`, { status }); setEditing(false); await load() } catch (requestError) { setError(requestError.response?.data?.detail || 'Unable to update session.') } }
  async function cancel() { if (!window.confirm('Delete this debate session?')) return; await api.delete(`/debates/${debateId}`); navigate('/debates') }
  if (!debate) return <div className="loading-state">Loading session...</div>
  const creator = debate.created_by === user.id
  return <section className="page-stack"><Link to="/debates" className="back-link">Back to sessions</Link><div className="page-heading"><div><p className="eyebrow">Debate session</p><h1>{debate.topic}</h1></div><span className={`status status-${debate.status}`}>{debate.status}</span></div><div className="detail-grid"><article className="detail-panel"><p className="eyebrow">Format</p><h2>{debate.format.replaceAll('_', ' ')}</h2><p>{debate.description || 'No description provided.'}</p>{creator && <div className="inline-form">{editing ? <><select value={status} onChange={(event) => setStatus(event.target.value)}><option>scheduled</option><option>active</option><option>completed</option><option>cancelled</option></select><button className="button" onClick={updateStatus}>Save status</button></> : <><button className="button secondary" onClick={() => setEditing(true)}>Edit status</button><button className="button danger" onClick={cancel}>Delete session</button></>}</div>}</article><article className="detail-panel"><p className="eyebrow">Participants</p>{participants.length === 0 ? <p className="muted">No participants yet.</p> : <div className="participant-list">{participants.map((participant) => <div className="participant" key={participant.id}><span>User #{participant.user_id} · {participant.position}</span>{(creator || participant.user_id === user.id) && <button className="text-button" onClick={() => removeParticipant(participant.user_id)}>Remove</button>}</div>)}</div>}<div className="inline-form"><select value={position} onChange={(event) => setPosition(event.target.value)}><option>neutral</option><option>for</option><option>against</option></select><button className="button" onClick={join}>Join session</button></div></article></div>{error && <p className="error-message">{error}</p>}</section>
}