import { useEffect, useState } from 'react'
import api from '../services/api'
import { useAuth } from '../context/AuthContext'

const empty = { experience_level: '', preferred_topics: [], presentation_domains: [], learning_goals: '', coaching_preferences: {} }
export default function Profile() {
  const { user, setUser } = useAuth(); const [form, setForm] = useState(empty); const [topics, setTopics] = useState(''); const [domains, setDomains] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { api.get('/profiles/me').then(({ data }) => { setForm(data); setTopics((data.preferred_topics || []).join(', ')); setDomains((data.presentation_domains || []).join(', ')) }).catch(() => setError('Unable to load profile.')).finally(() => setLoading(false)) }, [])
  async function submit(event) { event.preventDefault(); setMessage(''); setError(''); try { const profile = { ...form, preferred_topics: topics.split(',').map((item) => item.trim()).filter(Boolean), presentation_domains: domains.split(',').map((item) => item.trim()).filter(Boolean) }; await api.put('/profiles/me', profile); const { data } = await api.put('/users/me', { name: form.name || user.name }); setUser(data); setMessage('Profile saved.') } catch (requestError) { setError(requestError.response?.data?.detail || 'Unable to save profile.') } }
  if (loading) return <div className="loading-state">Loading profile...</div>
  return <section className="page-stack"><p className="eyebrow">Account / profile</p><h1>Your context.</h1><p className="lede">Keep your goals and practice preferences close at hand.</p><form className="form-card wide" onSubmit={submit}><label>Name<input value={form.name ?? user.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Email<input value={user.email} disabled /></label><label>Experience level<input value={form.experience_level || ''} onChange={(event) => setForm({ ...form, experience_level: event.target.value })} /></label><label>Preferred topics<input value={topics} onChange={(event) => setTopics(event.target.value)} placeholder="climate, technology, education" /></label><label>Presentation domains<input value={domains} onChange={(event) => setDomains(event.target.value)} placeholder="classroom, work, competition" /></label><label>Learning goals<textarea value={form.learning_goals || ''} onChange={(event) => setForm({ ...form, learning_goals: event.target.value })} rows="4" /></label>{error && <p className="error-message">{error}</p>}{message && <p className="success-message">{message}</p>}<button className="button">Save profile</button></form></section>
}