# Generated by Django 6.1.1 on 2026-09-13 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebateSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_topic_title', models.CharField(blank=True, default='', max_length=500)),
                ('format', models.CharField(choices=[('OXFORD', 'Oxford Parliamentary'), ('LINCOLN_DOUGLAS', 'Lincoln-Douglas'), ('PARLIAMENTARY', 'British Parliamentary')], default='OXFORD', max_length=50)),
                ('user_stance', models.CharField(choices=[('AFFIRMATIVE', 'Affirmative'), ('NEGATIVE', 'Negative')], default='AFFIRMATIVE', max_length=20)),
                ('ai_stance', models.CharField(choices=[('AFFIRMATIVE', 'Affirmative'), ('NEGATIVE', 'Negative')], default='NEGATIVE', max_length=20)),
                ('ai_persona', models.CharField(default='Socratic Inquisitor', max_length=100)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebateTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(default='TECHNOLOGY', max_length=100)),
                ('difficulty', models.CharField(default='COLLEGIATE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebateTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.IntegerField(default=1)),
                ('speaker', models.CharField(max_length=10)),
                ('transcript', models.TextField()),
                ('turn_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['turn_number', 'created_at'],
            },
        ),
    ]
