# Generated by Django 6.1.1 on 2026-09-13 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debatesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debatesession',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='debates.debatetopic'),
        ),
        migrations.AddField(
            model_name='debateturn',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='debates.debatesession'),
        ),
    ]
