# Generated by Django 6.1.1 on 2026-09-13 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField()),
                ('context', models.TextField(blank=True, default='')),
                ('claim', models.TextField()),
                ('grounds', models.TextField()),
                ('warrant', models.TextField()),
                ('qualifier', models.CharField(default='Universal', max_length=255)),
                ('logic_score', models.IntegerField(default=70)),
                ('evidence_score', models.IntegerField(default=70)),
                ('persuasiveness_score', models.IntegerField(default=70)),
                ('clarity_score', models.IntegerField(default=70)),
                ('overall_score', models.IntegerField(default=70)),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterArgument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('perspective', models.CharField(max_length=100)),
                ('counter_claim', models.TextField()),
                ('counter_evidence', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='LogicalFallacyInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fallacy_type', models.CharField(max_length=100)),
                ('excerpt', models.TextField()),
                ('explanation', models.TextField()),
                ('suggested_correction', models.TextField(blank=True, default='')),
            ],
        ),
    ]
