# Generated by Django 6.1.1 on 2026-09-13 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arguments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='counterargument',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterarguments', to='arguments.argumentanalysis'),
        ),
        migrations.AddField(
            model_name='logicalfallacyinstance',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallacies', to='arguments.argumentanalysis'),
        ),
    ]
