# Generated by Django 6.1.1 on 2026-09-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentanalysis',
            name='backing',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='argumentanalysis',
            name='rebuttal',
            field=models.TextField(blank=True, default=''),
        ),
    ]
